In [10]:
import pandas as pd

In [11]:
traffic = pd.read_csv(r'Traffic.csv')
traffic

   Weather Times of Week Time of day Traffic Jam
0    Clear       Workday     Morning         Yes
1    Clear       Workday      Lunch           No
2    Clear       Workday     Evening         Yes
3    Clear       Weekend     Morning          No
4    Clear       Weekend      Lunch           No
5    Clear       Weekend     Evening          No
6    Rainy       Workday     Morning         Yes
7    Rainy       Workday      Lunch          Yes
8    Rainy       Workday     Evening         Yes
9    Rainy       Weekend     Morning          No
10   Rainy       Weekend      Lunch           No
11   Rainy       Weekend     Evening          No
12   Snowy       Workday     Morning         Yes
13   Snowy       Workday      Lunch          Yes
14   Snowy       Workday     Evening         Yes
15   Snowy       Weekend     Morning         Yes
16   Snowy       Weekend      Lunch           No
17   Snowy       Weekend     Evening         Yes

In [12]:
x = traffic.iloc[:, :4].values
x

array([['Clear', 'Workday', 'Morning', 'Yes'],
       ['Clear', 'Workday', 'Lunch ', 'No'],
       ['Clear', 'Workday', 'Evening', 'Yes'],
       ['Clear', 'Weekend', 'Morning', 'No'],
       ['Clear', 'Weekend', 'Lunch ', 'No'],
       ['Clear', 'Weekend', 'Evening', 'No'],
       ['Rainy', 'Workday', 'Morning', 'Yes'],
       ['Rainy', 'Workday', 'Lunch ', 'Yes'],
       ['Rainy', 'Workday', 'Evening', 'Yes'],
       ['Rainy', 'Weekend', 'Morning', 'No'],
       ['Rainy', 'Weekend', 'Lunch ', 'No'],
       ['Rainy', 'Weekend', 'Evening', 'No'],
       ['Snowy', 'Workday', 'Morning', 'Yes'],
       ['Snowy', 'Workday', 'Lunch ', 'Yes'],
       ['Snowy', 'Workday', 'Evening', 'Yes'],
       ['Snowy', 'Weekend', 'Morning', 'Yes'],
       ['Snowy', 'Weekend', 'Lunch ', 'No'],
       ['Snowy', 'Weekend', 'Evening', 'Yes']], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [14]:
for i in range(4):
    x[:,i] = LabelEncoder().fit_transform(x[:, i])
x

array([[0, 1, 2, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 2, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 2, 1],
       [1, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 2, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [2, 1, 2, 1],
       [2, 1, 1, 1],
       [2, 1, 0, 1],
       [2, 0, 2, 1],
       [2, 0, 1, 0],
       [2, 0, 0, 1]], dtype=object)

In [15]:
onehotencoder= OneHotEncoder()    
x= onehotencoder.fit_transform(x[:,[3]]).toarray()  
x

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [16]:
traffic=pd.DataFrame(traffic)
traffic

   Weather Times of Week Time of day Traffic Jam
0        0             1           2           1
1        0             1           1           0
2        0             1           0           1
3        0             0           2           0
4        0             0           1           0
5        0             0           0           0
6        1             1           2           1
7        1             1           1           1
8        1             1           0           1
9        1             0           2           0
10       1             0           1           0
11       1             0           0           0
12       2             1           2           1
13       2             1           1           1
14       2             1           0           1
15       2             0           2           1
16       2             0           1           0
17       2             0           0           1

In [17]:
y = traffic["Traffic Jam"]
x = traffic.drop("Traffic Jam", axis = 1)
x

   Weather Times of Week Time of day
0        0             1           2
1        0             1           1
2        0             1           0
3        0             0           2
4        0             0           1
5        0             0           0
6        1             1           2
7        1             1           1
8        1             1           0
9        1             0           2
10       1             0           1
11       1             0           0
12       2             1           2
13       2             1           1
14       2             1           0
15       2             0           2
16       2             0           1
17       2             0           0

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [21]:
from sklearn.tree import DecisionTreeRegressor
decisionTreeRegressor = DecisionTreeRegressor()
decisionTreeRegressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [25]:
y_pred = decisionTreeRegressor.predict(x_test)

In [27]:
from sklearn.metric import classification_report

ModuleNotFoundError: No module named 'sklearn.metric'